package com.example.gramasanjeevini.models

// ── Supported languages ───────────────────────────────────────────────────────
enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en",  "English",  "English"),
    KANNADA("kn",  "Kannada",  "ಕನ್ನಡ"),
    HINDI(  "hi",  "Hindi",    "हिंदी"),
    TELUGU( "te",  "Telugu",   "తెలుగు"),
    TAMIL(  "ta",  "Tamil",    "தமிழ்")
}

// ── All UI strings per language ───────────────────────────────────────────────
data class AppStrings(
    val appName: String,
    val tagline: String,
    val signIn: String,
    val createAccount: String,
    val fullName: String,
    val phoneNumber: String,
    val email: String,
    val emailOptional: String,
    val password: String,
    val confirmPassword: String,
    val iAmA: String,
    val villager: String,
    val pharmacist: String,
    val enterNetwork: String,
    val dontHaveAccount: String,
    val alreadyHaveAccount: String,
    val signInBtn: String,
    val createAccountBtn: String,
    val search: String,
    val searchPlaceholder: String,
    val symptomPlaceholder: String,
    val bySymptom: String,
    val medicineName: String,
    val emergency: String,
    val expiryWatch: String,
    val map: String,
    val dashboard: String,
    val stock: String,
    val network: String,
    val lifeSaving: String,
    val essential: String,
    val general: String,
    val inStock: String,
    val callShop: String,
    val aiHealthGuide: String,
    val nearbyShops: String,
    val addMedicine: String,
    val saveToNetwork: String,
    val quantity: String,
    val expiryDate: String,
    val category: String,
    val shop: String,
    val welcomeBack: String,
    val logout: String,
    val noResults: String,
    val findingShops: String,
    val grantPermission: String,
    val locationNeeded: String,
    val navigate: String,
    val call: String,
    val selectLanguage: String
)

// ── English ───────────────────────────────────────────────────────────────────
val stringsEn = AppStrings(
    appName          = "GramaSanjeevini",
    tagline          = "RURAL PHARMACY NETWORK",
    signIn           = "Sign In",
    createAccount    = "Create Account",
    fullName         = "Full Name *",
    phoneNumber      = "Phone Number *",
    email            = "Email Address",
    emailOptional    = "Email Address (optional)",
    password         = "Password *",
    confirmPassword  = "Confirm Password *",
    iAmA             = "I am a",
    villager         = "Villager",
    pharmacist       = "Pharmacist",
    enterNetwork     = "Enter Network",
    dontHaveAccount  = "Don't have an account?",
    alreadyHaveAccount = "Already have an account?",
    signInBtn        = "Sign In",
    createAccountBtn = "Create Account",
    search           = "Search",
    searchPlaceholder = "Search medicine, shop or village…",
    symptomPlaceholder = "Describe symptom e.g. fever, stomach pain…",
    bySymptom        = "By Symptom",
    medicineName     = "Medicine Name",
    emergency        = "Emergency",
    expiryWatch      = "Expiry",
    map              = "Map",
    dashboard        = "Dashboard",
    stock            = "Stock",
    network          = "Network",
    lifeSaving       = "LIFE SAVING",
    essential        = "Essential",
    general          = "General",
    inStock          = "in stock",
    callShop         = "Call Shop",
    aiHealthGuide    = "AI Health Guide",
    nearbyShops      = "medical shops nearby",
    addMedicine      = "Add Medicine",
    saveToNetwork    = "Save to Network",
    quantity         = "Quantity in Stock *",
    expiryDate       = "Expiry Date *",
    category         = "Category *",
    shop             = "Shop *",
    welcomeBack      = "Welcome back,",
    logout           = "Logout",
    noResults        = "No medicines found",
    findingShops     = "Finding medical shops…",
    grantPermission  = "Grant Permission",
    locationNeeded   = "Location Access Needed",
    navigate         = "Navigate",
    call             = "Call",
    selectLanguage   = "Select Language"
)

// ── Kannada ───────────────────────────────────────────────────────────────────
val stringsKn = AppStrings(
    appName          = "ಗ್ರಾಮ ಸಂಜೀವಿನಿ",
    tagline          = "ಗ್ರಾಮೀಣ ಔಷಧಾಲಯ ಜಾಲ",
    signIn           = "ಸೈನ್ ಇನ್",
    createAccount    = "ಖಾತೆ ತೆರೆಯಿರಿ",
    fullName         = "ಪೂರ್ಣ ಹೆಸರು *",
    phoneNumber      = "ಫೋನ್ ಸಂಖ್ಯೆ *",
    email            = "ಇಮೇಲ್",
    emailOptional    = "ಇಮೇಲ್ (ಐಚ್ಛಿಕ)",
    password         = "ಪಾಸ್‌ವರ್ಡ್ *",
    confirmPassword  = "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ *",
    iAmA             = "ನಾನು",
    villager         = "ಗ್ರಾಮಸ್ಥ",
    pharmacist       = "ಔಷಧಿ ಅಂಗಡಿಯವರು",
    enterNetwork     = "ಜಾಲಕ್ಕೆ ಪ್ರವೇಶಿಸಿ",
    dontHaveAccount  = "ಖಾತೆ ಇಲ್ಲವೇ?",
    alreadyHaveAccount = "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
    signInBtn        = "ಸೈನ್ ಇನ್",
    createAccountBtn = "ಖಾತೆ ತೆರೆಯಿರಿ",
    search           = "ಹುಡುಕಿ",
    searchPlaceholder = "ಔಷಧಿ, ಅಂಗಡಿ ಅಥವಾ ಊರು ಹುಡುಕಿ…",
    symptomPlaceholder = "ರೋಗಲಕ್ಷಣ ಹೇಳಿ: ಜ್ವರ, ಹೊಟ್ಟೆ ನೋವು…",
    bySymptom        = "ರೋಗಲಕ್ಷಣದಿಂದ",
    medicineName     = "ಔಷಧಿ ಹೆಸರು",
    emergency        = "ತುರ್ತು",
    expiryWatch      = "ಅವಧಿ",
    map              = "ನಕ್ಷೆ",
    dashboard        = "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    stock            = "ಸ್ಟಾಕ್",
    network          = "ಜಾಲ",
    lifeSaving       = "ಜೀವ ರಕ್ಷಕ",
    essential        = "ಅಗತ್ಯ",
    general          = "ಸಾಮಾನ್ಯ",
    inStock          = "ಸ್ಟಾಕ್‌ನಲ್ಲಿದೆ",
    callShop         = "ಅಂಗಡಿಗೆ ಕರೆ ಮಾಡಿ",
    aiHealthGuide    = "AI ಆರೋಗ್ಯ ಮಾರ್ಗದರ್ಶಿ",
    nearbyShops      = "ಹತ್ತಿರದ ಔಷಧಿ ಅಂಗಡಿಗಳು",
    addMedicine      = "ಔಷಧಿ ಸೇರಿಸಿ",
    saveToNetwork    = "ಜಾಲಕ್ಕೆ ಉಳಿಸಿ",
    quantity         = "ಸ್ಟಾಕ್ ಪ್ರಮಾಣ *",
    expiryDate       = "ಅವಧಿ ಮುಕ್ತಾಯ ದಿನಾಂಕ *",
    category         = "ವರ್ಗ *",
    shop             = "ಅಂಗಡಿ *",
    welcomeBack      = "ಸ್ವಾಗತ,",
    logout           = "ಲಾಗ್ ಔಟ್",
    noResults        = "ಔಷಧಿ ಸಿಗಲಿಲ್ಲ",
    findingShops     = "ಔಷಧಿ ಅಂಗಡಿಗಳನ್ನು ಹುಡುಕುತ್ತಿದೆ…",
    grantPermission  = "ಅನುಮತಿ ನೀಡಿ",
    locationNeeded   = "ಸ್ಥಳ ಅನುಮತಿ ಬೇಕು",
    navigate         = "ದಾರಿ ತೋರಿಸಿ",
    call             = "ಕರೆ ಮಾಡಿ",
    selectLanguage   = "ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ"
)

// ── Hindi ─────────────────────────────────────────────────────────────────────
val stringsHi = AppStrings(
    appName          = "ग्राम संजीवनी",
    tagline          = "ग्रामीण दवाखाना नेटवर्क",
    signIn           = "साइन इन",
    createAccount    = "खाता बनाएं",
    fullName         = "पूरा नाम *",
    phoneNumber      = "फोन नंबर *",
    email            = "ईमेल",
    emailOptional    = "ईमेल (वैकल्पिक)",
    password         = "पासवर्ड *",
    confirmPassword  = "पासवर्ड की पुष्टि करें *",
    iAmA             = "मैं हूं",
    villager         = "ग्रामीण",
    pharmacist       = "दवाखाना मालिक",
    enterNetwork     = "नेटवर्क में प्रवेश करें",
    dontHaveAccount  = "खाता नहीं है?",
    alreadyHaveAccount = "पहले से खाता है?",
    signInBtn        = "साइन इन",
    createAccountBtn = "खाता बनाएं",
    search           = "खोजें",
    searchPlaceholder = "दवाई, दुकान या गाँव खोजें…",
    symptomPlaceholder = "लक्षण बताएं: बुखार, पेट दर्द…",
    bySymptom        = "लक्षण से खोजें",
    medicineName     = "दवाई का नाम",
    emergency        = "आपातकाल",
    expiryWatch      = "एक्सपायरी",
    map              = "नक्शा",
    dashboard        = "डैशबोर्ड",
    stock            = "स्टॉक",
    network          = "नेटवर्क",
    lifeSaving       = "जीवन रक्षक",
    essential        = "जरूरी",
    general          = "सामान्य",
    inStock          = "स्टॉक में है",
    callShop         = "दुकान को कॉल करें",
    aiHealthGuide    = "AI स्वास्थ्य गाइड",
    nearbyShops      = "पास की दवाई दुकानें",
    addMedicine      = "दवाई जोड़ें",
    saveToNetwork    = "नेटवर्क में सेव करें",
    quantity         = "स्टॉक मात्रा *",
    expiryDate       = "एक्सपायरी तारीख *",
    category         = "श्रेणी *",
    shop             = "दुकान *",
    welcomeBack      = "स्वागत है,",
    logout           = "लॉग आउट",
    noResults        = "दवाई नहीं मिली",
    findingShops     = "दवाई दुकानें ढूंढ रहे हैं…",
    grantPermission  = "अनुमति दें",
    locationNeeded   = "स्थान की अनुमति चाहिए",
    navigate         = "रास्ता दिखाएं",
    call             = "कॉल करें",
    selectLanguage   = "भाषा चुनें"
)

// ── Telugu ────────────────────────────────────────────────────────────────────
val stringsTe = AppStrings(
    appName          = "గ్రామ సంజీవని",
    tagline          = "గ్రామీణ ఔషధాలయ నెట్‌వర్క్",
    signIn           = "సైన్ ఇన్",
    createAccount    = "ఖాతా తెరవండి",
    fullName         = "పూర్తి పేరు *",
    phoneNumber      = "ఫోన్ నంబర్ *",
    email            = "ఇమెయిల్",
    emailOptional    = "ఇమెయిల్ (ఐచ్ఛికం)",
    password         = "పాస్‌వర్డ్ *",
    confirmPassword  = "పాస్‌వర్డ్ నిర్ధారించండి *",
    iAmA             = "నేను",
    villager         = "గ్రామస్థుడు",
    pharmacist       = "మందుల దుకాణదారు",
    enterNetwork     = "నెట్‌వర్క్‌లోకి ప్రవేశించండి",
    dontHaveAccount  = "ఖాతా లేదా?",
    alreadyHaveAccount = "ఇప్పటికే ఖాతా ఉందా?",
    signInBtn        = "సైన్ ఇన్",
    createAccountBtn = "ఖాతా తెరవండి",
    search           = "వెతకండి",
    searchPlaceholder = "మందు, దుకాణం లేదా గ్రామం వెతకండి…",
    symptomPlaceholder = "లక్షణం చెప్పండి: జ్వరం, కడుపు నొప్పి…",
    bySymptom        = "లక్షణం ద్వారా",
    medicineName     = "మందు పేరు",
    emergency        = "అత్యవసరం",
    expiryWatch      = "గడువు",
    map              = "మ్యాప్",
    dashboard        = "డాష్‌బోర్డ్",
    stock            = "స్టాక్",
    network          = "నెట్‌వర్క్",
    lifeSaving       = "జీవన రక్షక",
    essential        = "అవసరమైన",
    general          = "సాధారణ",
    inStock          = "స్టాక్‌లో ఉంది",
    callShop         = "దుకాణానికి కాల్ చేయండి",
    aiHealthGuide    = "AI ఆరోగ్య గైడ్",
    nearbyShops      = "సమీప మందుల దుకాణాలు",
    addMedicine      = "మందు జోడించండి",
    saveToNetwork    = "నెట్‌వర్క్‌కు సేవ్ చేయండి",
    quantity         = "స్టాక్ పరిమాణం *",
    expiryDate       = "గడువు తేదీ *",
    category         = "వర్గం *",
    shop             = "దుకాణం *",
    welcomeBack      = "స్వాగతం,",
    logout           = "లాగ్ అవుట్",
    noResults        = "మందు దొరకలేదు",
    findingShops     = "మందుల దుకాణాలు వెతుకుతున్నాం…",
    grantPermission  = "అనుమతి ఇవ్వండి",
    locationNeeded   = "స్థాన అనుమతి అవసరం",
    navigate         = "దారి చూపించు",
    call             = "కాల్ చేయండి",
    selectLanguage   = "భాష ఎంచుకోండి"
)

// ── Tamil ─────────────────────────────────────────────────────────────────────
val stringsTa = AppStrings(
    appName          = "கிராம சஞ்சீவினி",
    tagline          = "கிராமப்புற மருந்தக வலைப்பின்னல்",
    signIn           = "உள்நுழைக",
    createAccount    = "கணக்கு உருவாக்கு",
    fullName         = "முழு பெயர் *",
    phoneNumber      = "தொலைபேசி எண் *",
    email            = "மின்னஞ்சல்",
    emailOptional    = "மின்னஞ்சல் (விருப்பத்தேர்வு)",
    password         = "கடவுச்சொல் *",
    confirmPassword  = "கடவுச்சொல் உறுதிப்படுத்து *",
    iAmA             = "நான்",
    villager         = "கிராமவாசி",
    pharmacist       = "மருந்தகக்காரர்",
    enterNetwork     = "வலைப்பின்னலில் நுழைக",
    dontHaveAccount  = "கணக்கு இல்லையா?",
    alreadyHaveAccount = "ஏற்கனவே கணக்கு உள்ளதா?",
    signInBtn        = "உள்நுழைக",
    createAccountBtn = "கணக்கு உருவாக்கு",
    search           = "தேடு",
    searchPlaceholder = "மருந்து, கடை அல்லது கிராமம் தேடு…",
    symptomPlaceholder = "அறிகுறி சொல்லுங்கள்: காய்ச்சல், வயிற்று வலி…",
    bySymptom        = "அறிகுறி மூலம்",
    medicineName     = "மருந்தின் பெயர்",
    emergency        = "அவசரம்",
    expiryWatch      = "காலாவதி",
    map              = "வரைபடம்",
    dashboard        = "டாஷ்போர்டு",
    stock            = "இருப்பு",
    network          = "வலைப்பின்னல்",
    lifeSaving       = "உயிர் காக்கும்",
    essential        = "அவசியமான",
    general          = "பொதுவான",
    inStock          = "இருப்பில் உள்ளது",
    callShop         = "கடைக்கு அழைக்கவும்",
    aiHealthGuide    = "AI சுகாதார வழிகாட்டி",
    nearbyShops      = "அருகிலுள்ள மருந்தகங்கள்",
    addMedicine      = "மருந்து சேர்க்கவும்",
    saveToNetwork    = "வலைப்பின்னலில் சேமி",
    quantity         = "இருப்பு அளவு *",
    expiryDate       = "காலாவதி தேதி *",
    category         = "வகை *",
    shop             = "கடை *",
    welcomeBack      = "வரவேற்கிறோம்,",
    logout           = "வெளியேறு",
    noResults        = "மருந்து கிடைக்கவில்லை",
    findingShops     = "மருந்தகங்களை தேடுகிறோம்…",
    grantPermission  = "அனுமதி வழங்கு",
    locationNeeded   = "இட அனுமதி தேவை",
    navigate         = "வழி காட்டு",
    call             = "அழைக்கவும்",
    selectLanguage   = "மொழி தேர்ந்தெடுக்கவும்"
)

// ── Get strings for language ──────────────────────────────────────────────────
fun getStrings(lang: AppLanguage): AppStrings = when (lang) {
    AppLanguage.KANNADA -> stringsKn
    AppLanguage.HINDI   -> stringsHi
    AppLanguage.TELUGU  -> stringsTe
    AppLanguage.TAMIL   -> stringsTa
    else                -> stringsEn
}
